version: '3.8'

services:
  mongo:
    image: mongo
    conatiner_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      -mongo-data:/data/db

  backend:
    build: ./backend    
    conatiner_name: backend
    ports:
     - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules   
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env  
    depends_on:
      - backend
volumes:
  mongo-data:                